name: Third-party licenses check
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
jobs:
  licenses-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # actions/setup-go does not setup the installed toolchain to be preferred over the system install,
      # which causes go-licenses to raise "Package ... does not have module info" errors.
      # for more information, https://github.com/google/go-licenses/issues/244#issuecomment-1885098633
      #
      # go-licenses has been pinned for automation use.
      - name: Check licenses
        run: |
          export GOROOT=$(go env GOROOT)
          export PATH=${GOROOT}/bin:$PATH
          go install github.com/google/go-licenses@5348b744d0983d85713295ea08a20cca1654a45e
          make licenses-check
